name: gnn_intro
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - pytorch_geometric
  - pyproj
  - contextily  >=1.3.0     # For basemaps
  - matplotlib  >=3.8       # For plotting
  - seaborn
  - pandas
  - numpy
  - networkx                # Underlying graph analysis
  - scikit-learn
  - jupyterlab
  - plotly
  - ipython
  - pip